-- Enable UUID extension (optional, but good practice in Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 2. Members Table
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  position TEXT,
  agency_lgu TEXT,
  province_region TEXT,
  mobile_number TEXT,
  email TEXT UNIQUE NOT NULL,
  website TEXT,
  photo_url TEXT,
  training_climate_change INTEGER DEFAULT 0,
  training_digitalization INTEGER DEFAULT 0,
  training_creative_industries INTEGER DEFAULT 0,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  last_seen TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Posts Table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Reactions Table
CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  image_url TEXT,
  stock INTEGER DEFAULT 0
);

-- 6. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT, -- 0 for admin, or references members(id)
  receiver_id BIGINT, -- 0 for all, or references members(id)
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  content TEXT,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Security: Enable Row Level Security (RLS)
ALTER TABLE admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE reactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- 9. Policies (Allowing the backend to function with the ANON key)
-- NOTE: In a production environment, it is highly recommended to use the SERVICE_ROLE_KEY 
-- on the backend to bypass RLS, and keep RLS restricted for the ANON key.
-- These policies allow basic operations required for the app to function.

DROP POLICY IF EXISTS "Allow all on admins" ON admins;
CREATE POLICY "Allow all on admins" ON admins FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on members" ON members;
CREATE POLICY "Allow all on members" ON members FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on posts" ON posts;
CREATE POLICY "Allow all on posts" ON posts FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on reactions" ON reactions;
CREATE POLICY "Allow all on reactions" ON reactions FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on products" ON products;
CREATE POLICY "Allow all on products" ON products FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on messages" ON messages;
CREATE POLICY "Allow all on messages" ON messages FOR ALL USING (true);
DROP POLICY IF EXISTS "Allow all on notifications" ON notifications;
CREATE POLICY "Allow all on notifications" ON notifications FOR ALL USING (true);

-- Seed Admin User (Password: admin123)
-- We use a fresh hash to ensure compatibility
DELETE FROM admins WHERE username IN ('admin', 'admin@lccad.com');
INSERT INTO admins (username, password)
VALUES 
  ('admin', '$2b$10$NgVxRQ5z22T43Mlzs6xs0eCzIcAVbMaIgcvHIx6N3oIKunwc0.gf6'),
  ('admin@lccad.com', '$2b$10$NgVxRQ5z22T43Mlzs6xs0eCzIcAVbMaIgcvHIx6N3oIKunwc0.gf6');
