-- Enable UUID extension (optional, but good practice in Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- 2. Members Table
CREATE TABLE IF NOT EXISTS members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  position TEXT,
  agency_lgu TEXT,
  province_region TEXT,
  mobile_number TEXT,
  email TEXT UNIQUE NOT NULL,
  website TEXT,
  photo_url TEXT,
  training_climate_change INTEGER DEFAULT 0,
  training_digitalization INTEGER DEFAULT 0,
  training_creative_industries INTEGER DEFAULT 0,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  last_seen TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Posts Table
CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  content TEXT,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Reactions Table
CREATE TABLE IF NOT EXISTS reactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(10, 2) NOT NULL,
  image_url TEXT,
  stock INTEGER DEFAULT 0
);

-- 6. Messages Table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT, -- 0 for admin, or references members(id)
  receiver_id BIGINT, -- 0 for all, or references members(id)
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members(id) ON DELETE CASCADE,
  content TEXT,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Seed Admin User (Password: admin123)
INSERT INTO admins (username, password)
VALUES 
  ('admin', '$2b$10$NgVxRQ5z22T43Mlzs6xs0eCzIcAVbMaIgcvHIx6N3oIKunwc0.gf6'),
  ('admin@lccad.com', '$2b$10$NgVxRQ5z22T43Mlzs6xs0eCzIcAVbMaIgcvHIx6N3oIKunwc0.gf6')
ON CONFLICT (username) DO NOTHING;

-- Enable Row Level Security (RLS) - Optional, but recommended for Supabase
-- For this specific app structure where the backend handles everything, RLS might not be strictly necessary if you are just using the Postgres connection string.
-- However, if you plan to use Supabase Client on the frontend, you'll need policies.
-- For now, we'll leave RLS disabled or default to allow the service role (backend) full access.
